services:
  birbnb-db:
    container_name: "birbnb-db"
    image: "postgres:16-alpine"
    env_file:
      - ./birbnb-backend/.env
    ports:
      - "5432:5432"
    volumes:
      - "birbnb-data:/var/lib/postgresql/data"

volumes:
  birbnb-data:
