services:
  postgres:
    container_name: "birbnb-postgres"
    image: "postgres:16-alpine"
    attach: false
    env_file:
      - ./birbnb-backend/.env
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  birbnb-backend:
    build: ./birbnb-backend
    container_name: birbnb-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./birbnb-backend/.env

  birbnb-frontend:
    container_name: birbnb-frontend
    build:
      context: ./birbnb-frontend
      args:
        - NODE_ENV
    env_file:
      - ./birbnb-frontend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "5173:80"
    depends_on:
      - birbnb-backend

volumes:
  postgres-data:
